name: Windows DLL

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.luaVersion }} on ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty" ]
        platform: [ "windows-2022" ] # "ubuntu-22.04", "macos-14", 
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ’msvc’
        if: ${{ startsWith(matrix.platform, 'windows') && !startsWith(matrix.luaVersion, 'luajit') }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup ‘lua’
        uses: luarocks/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
          buildCache: false
      - name: Setup ‘luarocks’
        # master branch until tagged release has luajit & msvcrt fixes
        uses: luarocks/gh-actions-luarocks@master
      - name: Make and install
        run: |
          luarocks make -- luasocket-scm-3.rockspec
        env:
          DEBUG: DEBUG
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v5
